### ISSUE TITLE
Rename crossminer/ossmeter to crossminer/crossminer

### ISSUE THREAD

**Issue by jurgenvinju** [crossminer/crossminer#49]

**Comment by borisbaldassari** [comment]
WARN: Also move crossminer/crossminer wiki to crossminer/ossmeter before deleting the former.

**Comment by davidediruscio** [comment]
There is only a hello world page in the crossminer/crossminer wiki. Thus, I guess we can simply rename the repository.

**Comment by borisbaldassari** [comment]
My bad; my comment was referring to what is actually in the internal-material wiki. Sorry! :-)

**Comment by tdegueul** [comment]
Seems like someone did the renaming already.
