### ISSUE TITLE
Missing user documentation for the Eclipse plugin

### ISSUE THREAD

**Issue by phkrief** [crossminer/crossminer#83]
A getting started documentation is missing to understand how to use some default features provided by the plugin once the plugin is installed.

-Thanks

**Comment by jdirocco** [comment]
Hi @phkrief ,
Does the [getting start guide](https://drive.google.com/file/d/1JUIpFTGTfZkS2VNufv-enKuGvC4xXna5/view?usp=sharing) close this issue?

**Comment by phkrief** [comment]
Dear @md2manoppello 
Actually, the document has been ported to GitHub: https://github.com/crossminer/scava-docs/blob/master/docs/user-guide/plugin/getting-started/index.md
So in terms of documentation, I guess it is a good start.
And we can close this issue.
Thanks again for your great support on that.

**Comment by davidediruscio** [comment]
Thanks Philippe. The link https://github.com/crossminer/scava-docs/raw/master/docs/user-guide/plugin/getting-started/images/Convert2Maven.png seems to be broken.

**Comment by phkrief** [comment]
Fixed! Thx
Kind regards
*—*
Philippe Krief, PhD
Research Relations Director | Eclipse Foundation, Inc.
Eclipse Foundation <http://www.eclipse.org/>: The Platform for Open
Innovation and Collaboration
M: +33 (0)6 21 01 06 81


Annastr. 46, D-64673 Zwingenberg
Handelsregister: Darmstadt HRB 92821
Managing Directors: Ralph Mueller, Mike Milinkovich, Gael Blondelle
