### ISSUE TITLE
project2dep-name doesn't expand properly

### ISSUE THREAD

**Issue by phkrief** [crossminer/crossminer#85]
When you ask to expand the widget project2dep-name to see the whole graph in the view, the graph stays partially
![project2dep-name](https://user-images.githubusercontent.com/6196602/57982273-6bb60800-7a43-11e9-8444-74d022475977.png)
 hidden

**Comment by valeriocos** [comment]
Thank you @phkrief for reporting this issue, I'll check it with @dlumbrer tomorrow.

**Comment by dlumbrer** [comment]
Hi @phkrief,

Thanks for reporting the issue. I was trying to replicate the problem but I couldn't. My behavior is right, I see the graph in all the available space (I tested it with Chrome and Firefox as well):

![Screenshot from 2019-05-20 11-21-38](https://user-images.githubusercontent.com/9249232/58010884-7cbd5280-7af1-11e9-9066-029c85e31a75.png)



Anyway, there is another way to see the visualization in a stand-alone way, you can click on the **Edit** button at the top of the page:

![Screenshot from 2019-05-20 11-23-59](https://user-images.githubusercontent.com/9249232/58011086-d887db80-7af1-11e9-80b5-aa81f7427b1e.png)

And then go to the visualization settings button (the gear button) and click on "Edit Visualization:

![Screenshot from 2019-05-20 11-25-46](https://user-images.githubusercontent.com/9249232/58011313-46cc9e00-7af2-11e9-9832-739f1aab108b.png)


Finally, you will be redirected to the visualization edit mode, and you can see the visualization bigger:

![Screenshot from 2019-05-20 11-26-02](https://user-images.githubusercontent.com/9249232/58011309-446a4400-7af2-11e9-9a51-0c099f6fa613.png)


Hope it works for you!

Thanks!

**Comment by phkrief** [comment]
Hi David,

I tried this morning to reproduce the isseu without success.
Sorry for the trouble.

Kind regards
—
Philippe Krief, PhD
Research Relations Director | Eclipse Foundation, Inc.
Eclipse Foundation <http://www.eclipse.org/>: The Platform for Open Innovation and Collaboration
M: +33 (0)6 21 01 06 81
 
Annastr. 46, D-64673 Zwingenberg
Handelsregister: Darmstadt HRB 92821
Managing Directors: Ralph Mueller, Mike Milinkovich, Chris Larocque

**Comment by valeriocos** [comment]
Thank you @phkrief for the feedback. Let's close this issue, we can reopen it in case the bug shows up again.
